name: Deploy frontend to Hostinger (manual)

on:
  workflow_dispatch:
    inputs:
      viteApiUrl:
        description: "VITE_API_URL to embed in build"
        required: false
        default: "https://trust-live.onrender.com/api"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build (Hostinger base=/)
        env:
          VITE_API_URL: ${{ github.event.inputs.viteApiUrl || 'https://trust-live.onrender.com/api' }}
        run: |
          node scripts/hostinger-build.cjs
          cp dist/index.html dist/404.html || true
          cat > dist/.htaccess <<'HTACCESS'
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
          HTACCESS

      - name: Deploy via FTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: frontend/dist/
          server-dir: ${{ secrets.HOSTINGER_REMOTE_DIR }}
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
