name: Deploy to GitHub Pages (TRUST) - DISABLED

on:
  # DISABLED - Using Hostinger deployment instead
  # push:
  #   branches: [ master, main ]
  #   paths:
  #     - 'frontend/**'
  #     - '.github/workflows/deploy-gh-pages.yml'
  # workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Build with base=/TRUST/
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          node -e "const fs=require('fs');const p='./vite.config.js';let s=fs.readFileSync(p,'utf8');s=s.replace(/\n\s*\/\/\s*base:\s*'\/TRAC1\/'[\s\S]*?\n/, '\n  base: \'/TRUST/\',\n');if(!/base:\s*'\/TRUST\//.test(s)) s=s.replace(/defineConfig\(\{/, 'defineConfig({\n  base: \"/TRUST/\",');fs.writeFileSync(p,s);"
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
          publish_branch: gh-pages

