name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ master, main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build with base=/TRUST/
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://api.trustclinicalservices.com' }}
        run: |
          # Update vite.config.js to set base path for GitHub Pages
          node -e "
          const fs = require('fs');
          const path = './vite.config.js';
          let content = fs.readFileSync(path, 'utf8');
          
          // Replace or add base configuration
          if (content.includes('base:')) {
            content = content.replace(/base:\s*['\"][^'\"]*['\"]/, 'base: \"/TRUST/\"');
          } else {
            content = content.replace(/export default defineConfig\(\{/, 'export default defineConfig({\n  base: \"/TRUST/\",');
          }
          
          fs.writeFileSync(path, content);
          console.log('Updated vite.config.js with base path');
          "
          
          npm run build
          
          # Create 404.html for SPA routing
          cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
          publish_branch: gh-pages