name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ master, main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: |
          npm run lint || echo "Linting completed with warnings"
          echo "Linting step completed"

      - name: Build for GitHub Pages
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://api.trustclinicalservices.com' }}
        run: |
          echo "Starting build process..."
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Current directory: $(pwd)"
          echo "Contents: $(ls -la)"
          
          # Build with correct base path for Trust-Live repository
          npm run build
          
          # Create 404.html for SPA routing (React Router)
          cp dist/index.html dist/404.html
          
          # List built files for debugging
          echo "Build completed. Contents of dist/:"
          ls -la dist/
          echo "Build step completed successfully"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
          publish_branch: gh-pages
          allow_empty_commit: true
          force_orphan: true